#      __  __                _____ __       _ __
#     / / / /__  _  ______ _/ ___// /______(_) /_____
#    / /_/ / _ \| |/_/ __ `/\__ \/ __/ ___/ / //_/ _ \
#   / __  /  __/>  </ /_/ /___/ / /_/ /  / / ,< /  __/
#  /_/ /_/\___/_/|_|\__,_//____/\__/_/  /_/_/|_|\___/
#     / __ \_________ ______/ /_(_)_______
#    / /_/ / ___/ __ `/ ___/ __/ / ___/ _ \
#   / ____/ /  / /_/ / /__/ /_/ / /__/  __/
#  /_/   /_/   \__,_/\___/\__/_/\___/\___/
version: 1.0
WinnerCoins: 100
CoinGrantMessage: "&aHai vinto %coins% Coins"